# Site settings
title: Paul Summers
subtitle: Postdoctoral Researcher
email: paul.summers@gatech.edu
description: MY PERSONAL PAGE
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Paul Summers
street_address: ""
city: Atlanta 
state: GA
zip_code: 30318
country: United States of America
phone:

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/somonesummers
gitlab_url:
googleplus_url:
instagram_url: https://www.instagram.com/somonesummers/
linkedin_url: https://www.linkedin.com/in/paul-summers-92428180
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown
